### ISSUE TITLE
TOML support planned

### ISSUE THREAD

**Issue by kakila** [Jakski/sphinxcontrib-autoyaml#17]
How difficult would it be to generalize/reuse your code to parse TOML files as well?

Now that [3.11 offers a core library to parse these files](https://docs.python.org/3/library/tomllib.html), I will be slowly abandoning YAML in python projects.

Are you planning a TOML extension for sphinx?

**Comment by Jakski** [comment]
I'm not quite sure what are the differences between YAML and TOML apart from syntax. Keep in mind that this extension doesn't parse YAML by itself. It relies on `ruamel.yaml` to handle all the details. This is crucial, since `ruamel.yaml` is responsible for providing parsing meta-data like line numbers - it goes far beyond just converting YAML files into Python structures.

I'm not planning to support TOML. This module isn't doing the actual hardwork like generating graph representation of documents. Such features are expected to be provided by external modules. To my knowledge `tomllib` doesn't provide them.
