### ISSUE TITLE
rendering "complex" keys

### ISSUE THREAD

**Issue by kakila** [Jakski/sphinxcontrib-autoyaml#19]
In the docs you mention that keys like "[1,2]"  are difficult to represent.

Why don't you just parse all keys as literal strings?  Why not representing everything with a literal string  as in the source YAML file?

**Comment by Jakski** [comment]
Technically it's possible, since `ruamel.yaml` attempts to resemble original document as close as possible, but keys are used as a single-line terms in definition list. Splitting into multiple lines would most likely make them unreadable. Difficulty lies in making it readable after rendering a document.
